version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: korean-fitness-db
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
      POSTGRES_DB: korean_fitness_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d korean_fitness_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: